variables:
  DOCFX_SOURCE_BRANCH_NAME: $CI_BUILD_REF_NAME  

stages:
  - build
  - release


build_lib_test:
  stage: build
  image: mono:5.8
  script:
    - ./build.sh
  tags:
    - docker
  except:
    - tags

build_lib_release:
  stage: build
  image: mono:5.8
  script:
    - export BUILD_VERSION=$(echo $CI_COMMIT_REF_NAME | sed  's/\([0-9]\+\.[0-9]\+\.[0-9]\+\)\-release$/\1/g')
    - echo $BUILD_VERSION
    - sed -i -e "s/0.5.1.0/$BUILD_VERSION.0/g" Assets/Plugins/Rayark/Mast/Properties/AssemblyInfo.cs
    - ./build.sh
  artifacts:
    expire_in: 5 yrs
    name: mast-unity-project
    paths:
      - build
  tags:
    - docker
  only:
    - /^.*-release$/

mast-release:
  stage: release
  image: bash
  script:
    - cp build/Assets/Plugins/Rayark/Mast/Rayark.Mast.dll .
  artifacts:
    expire_in: 5 yrs
    paths:
      - Rayark.Mast.dll
  dependencies:
    - build_lib_release
  tags:
    - docker
  only:
    - /^.*-release$/

document:
  stage: build
  image: alvinsay/docfx:2.32.1
  script:
    - docfx doc/docfx.json
    - mv doc/_site public
  artifacts:
    expire_in: 5 yrs
    paths:
      - public                       # Upload the directory
  tags:
    - docker
  only:
    - /^.*-release$/


pages:
  stage: release
  image: alvinsay/docfx:2.32.1
  script:
    - docfx doc/docfx.json
    - mv doc/_site public
  artifacts:
    paths:
      - public                       # Upload the directory
  tags:
    - docker
  only:
    - master
